In [1]:
#Load Dataset Correctly
import pandas as pd

df = pd.read_csv("spam.csv", encoding="latin-1")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'spam.csv'

In [ ]:
#Check Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [ ]:
#Remove Useless Columns
df = df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])

In [ ]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Rename Columns
df = df.rename(columns={
    'v1':'label',
    'v2':'message'
})

In [ ]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Check Missing Values
df.isnull().sum()

label      0
message    0
dtype: int64

In [ ]:
#remove duplicates msg
df = df.drop_duplicates()

In [ ]:
df.shape

(5169, 2)

In [ ]:
#Convert Labels to Numbers
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

In [ ]:
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Check Class Distribution
df['label'].value_counts()

label
0    4516
1     653
Name: count, dtype: int64

In [4]:
#First load the cleaned dataset
import pandas as pd

df = pd.read_csv("../spam.csv", encoding="latin-1")

df = df[['v1','v2']]
df.columns = ['label','message']

df['label'] = df['label'].map({'ham':0,'spam':1})

df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [5]:
#Import NLP Libraries
import nltk
import re

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [6]:
#Download stopwords once:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [7]:
#Create Stemmer stemming converts words to their root form.
ps = PorterStemmer()

In [8]:
#Create Text Cleaning Function this function perform all preprocessing step
def preprocess_text(text):
    # convert to lowercase
    text = text.lower()
    # remove numbers and punctuation
    text = re.sub('[^a-zA-Z]', ' ', text)
    # split words
    words = text.split()
    # remove stopwords and apply stemming
    words = [ps.stem(word) for word in words if word not in stopwords.words('english')]
    # join words again
    text = " ".join(words)
    return text

In [9]:
#Apply Preprocessing to Dataset
df['clean_message'] = df['message'].apply(preprocess_text)
df.head()

,label,message,clean_message
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [10]:
df[['message','clean_message']].head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [11]:
df.shape

(5572, 3)

In [12]:
df.to_csv("processed_spam.csv", index=False)

In [14]:
#Import Feature Extraction Library
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
#Create Vectorizer
cv = CountVectorizer()

In [16]:
#Convert Text → Numbers
X = cv.fit_transform(df['clean_message'])

In [17]:
X.shape

(5572, 6221)

In [18]:
#Create Target Variable Target variable is spam or not spam.
y = df['label']

In [19]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

In [20]:
#split training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
#check shapes
print(X_train.shape)
print(X_test.shape)

(4457, 6221)
(1115, 6221)

In [21]:
#1 Data Cleaning 
#2 Text Preprocessing 
#3 Feature Extraction
#4 Train Test Split

In [22]:
#train model (multinomial naive bayes)
from sklearn.naive_bayes import MultinomialNB
#create model
model = MultinomialNB()
#train model
model.fit(X_train, y_train)

MultinomialNB()

In [23]:
#make prediction
y_pred = model.predict(X_test)

In [24]:
#check accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9739910313901345

In [25]:
#Naive Bayes is excellent for spam detection.

In [26]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[945  20]
 [  9 141]]

In [27]:
#test custom msg
msg = ["Congratulations you won free lottery"]
msg_vector = cv.transform(msg)
prediction = model.predict(msg_vector)

print(prediction)

[1]

In [28]:
# i completed Input Message
#Text Preprocessing
#Bag of Words
#Multinomial Naive Bayes
#Spam / Not Spam Prediction

In [29]:
#Save the Trained Model
#Naive Bayes model CountVectorizer both are required for prediction.

In [30]:
import pickle
#save the model
pickle.dump(model, open('../model/spam_model.pkl', 'wb'))
#save the vectorizer
pickle.dump(cv, open('../model/vectorizer.pkl', 'wb'))

In [31]:
#test saved model
loaded_model = pickle.load(open('../model/spam_model.pkl','rb'))

loaded_vectorizer = pickle.load(open('../model/vectorizer.pkl','rb'))

In [32]:
test_msg = ["Free entry in lottery"]

vec = loaded_vectorizer.transform(test_msg)

prediction = loaded_model.predict(vec)

print(prediction)

[1]